In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [31]:
A=np.array([[1,2],[2,1],[1,1]])
b=np.array([5,6,4])

In [6]:
np.dot(np.dot(np.linalg.inv(np.dot(A.T,A)),A.T),b)

array([2.36363636, 1.36363636])

In [33]:
A=np.matrix('1.,-2;1,5;2,1;1,1')
b=np.array([1.,13.1,7.9,5.1])

In [19]:
np.dot(np.dot(np.linalg.inv(np.dot(A.T,A)),A.T),b)

matrix([[3.45856354, 1.79834254]])

In [20]:
np.dot(A.T,A)

matrix([[ 7.,  6.],
        [ 6., 31.]])

In [22]:
A.T*A

matrix([[ 7.,  6.],
        [ 6., 31.]])

In [24]:
np.dot(np.linalg.inv(np.dot(A.T,A)),A.T)

matrix([[ 0.23756906,  0.00552486,  0.30939227,  0.13812155],
        [-0.11049724,  0.16022099, -0.02762431,  0.00552486]])

In [37]:
np.multiply(np.linalg.inv(A.T*A)*A.T,b)

matrix([[ 0.23756906,  0.07237569,  2.4441989 ,  0.70441989],
        [-0.11049724,  2.09889503, -0.21823204,  0.0281768 ]])

In [36]:
np.linalg.inv(A.T*A)*A.T

matrix([[ 0.23756906,  0.00552486,  0.30939227,  0.13812155],
        [-0.11049724,  0.16022099, -0.02762431,  0.00552486]])